includes = ['/home/jared/dev/src']
env = Environment(CPPPATH = includes,
                  tools = ['default', 'intelc'],
                  CPPFLAGS = '-O3')

# create a library 
sources = ['Path.cpp']
env.Library('path', sources)
