import os
import glob

# find all .cpps in the current directory
sources = []
pattern = os.path.join(os.getcwd(), "*.cpp")
for fullpath in glob.glob(pattern):
  basename = os.path.basename(fullpath)
  sources.append(basename)

# create a library 
Import('env')
env.Library('primitives', sources)

