import os
import glob

# find all .cpps in the current directory
sources = []
extensions = ['.cpp']
for ext in extensions:
  pattern = os.path.join(os.getcwd(), "*" + ext)
  for fullpath in glob.glob(pattern):
    basename = os.path.basename(fullpath)
    sources.append(basename)

# compile shared objects
Import('env')

sharedObjects = env.SharedObject(sources)
Return('sharedObjects')

