import os
import glob

# find all .cpps in the current directory
sources = []
extensions = ['.cpp', '.cu']
for ext in extensions:
  pattern = os.path.join(os.getcwd(), "*" + ext)
  for fullpath in glob.glob(pattern):
    basename = os.path.basename(fullpath)
    sources.append(basename)

sources.append("../../../cudamt/CudaMersenneTwister_mInitialState.cpp")
sources.append("../../../cudamt/CudaMersenneTwister.cpp")
sources.append("../../../cudamt/mersenneTwister.cu")

# create a library 
Import('env')
env.Library('cudanumeric', sources)

