#exec open('../../../build.py')

includes = ['/home/jared/dev/src']
env = Environment(CPPPATH = includes,
                  tools = ['default', 'intelc'],
                  CPPFLAGS = '-O3')

# create a library
sources = ['FunctionAllocator.cpp',
           'HemisphericalEmission.cpp',
           'Lambertian.cpp',
           'Material.cpp',
           'PerspectiveSensor.cpp',
           'ScatteringDistributionFunction.cpp']
env.SharedLibrary('shading', sources)

