import os
import glob

# XXX fix this path issue
if os.name == 'posix':
  bld = Builder(action = '/home/jared/dev/src/gotham/shaders/pbslc.py $SOURCE')
elif os.name == 'nt':
  bld = Builder(action = 'c:/dev/src/gotham/shaders/pbslc.py $SOURCE')
env = Environment(BUILDERS = {'Material' : bld},
                  suffix = '.so',
                  src_suffix = '.pbsl')

# find all .pbsls in the current directory
sources = []
pattern = os.path.join(os.getcwd(), "*.pbsl")
for fullpath in glob.glob(pattern):
  basename = os.path.basename(fullpath)
  sources.append(basename)

for s in sources:
  basename = os.path.basename(s)
  env.Material(basename + '.so',s)

