import os
import glob

if os.name == 'nt':
  bld = Builder(action = 'pbslc.bat $SOURCE')
else:
  bld = Builder(action = 'pbslc $SOURCE')

env = Environment(BUILDERS = {'Material' : bld},
                  suffix = '.so',
                  src_suffix = '.pbsl')

# set GOTHAMHOME in the scons environment
env['ENV']['GOTHAMHOME'] = os.environ['GOTHAMHOME']

# add the GOTHAM bin directory to the path
env.AppendENVPath('PATH', os.path.join(env['ENV']['GOTHAMHOME'], 'bin'))

print env['ENV']['PATH']

# find all .pbsls in the current directory
sources = []
pattern = os.path.join(os.getcwd(), "*.pbsl")
for fullpath in glob.glob(pattern):
  basename = os.path.basename(fullpath)
  sources.append(basename)

for s in sources:
  env.Material(s.split('.')[0] + '.so',s)

