Import('env')
SConscript(['primitives/SConscript',
            'shading/SConscript',
            'renderers/SConscript',
            'numeric/SConscript',
            'api/SConscript'],
           exports = {'env':env})
