includes = ['/home/jared/dev/src']
env = Environment(CPPPATH = includes,
                  tools = ['default', 'intelc'],
                  CPPFLAGS = '-O3')

# create a library
sources = ['Surface.cpp', 'Mesh.cpp']
env.Library('surfaces', sources)

