#!/usr/bin/env python
import sys

def options():
  pass

def usage():
  print 'Usage: gotham file0 [file1 ...]'
  options()
  exit(-1)

# we may want to do this after parsing the arguments
# so we can intercept a "silence" command
from api import *

# execute files in arguments
if len(sys.argv) < 2:
  print 'Error: Please specify at least one input scene file.'
  usage()
  exit(-1)

for arg in sys.argv[1:]:
  exec open(arg)

