import os
import glob

Import('env')

sources = ['Gotham.cpp', 'exportApi.cpp']

# create shared objects
sharedObjects = env.SharedObject(sources)
Return('sharedObjects')

## build imgstat
#env.Program('imgstat', 'imgstat.cpp')
#
## build imgclean
#env.Program('imgclean', 'imgclean.cpp')
#

